import type {
  Club,
  ClubEvent,
  ClubMember,
  ClubPost,
} from "@/lib/clubs-types";

/* ── Mock Clubs ──────────────────────────── */
export const MOCK_CLUBS: Club[] = [
  {
    id: 1,
    slug: "inpt-tech-club",
    name: "INPT Tech Club",
    description:
      "Le club technique de l'INPT. Nous organisons des workshops, des hackathons et des projets collaboratifs autour des technologies modernes: IA, Cloud, DevOps, Web, Mobile et plus encore.\n\n## Notre mission\nDémocratiser l'accès aux technologies de pointe pour tous les étudiants de l'INPT.\n\n## Ce que nous offrons\n- **Workshops hebdomadaires** sur des technos trending\n- **Hackathons semestriels** avec des prix\n- **Mentorat** par des professionnels du secteur\n- **Projets open-source** collaboratifs",
    short_description:
      "Le club technique de l'INPT — workshops, hackathons & projets tech.",
    category: "tech",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2019,
    member_count: 127,
    event_count_this_year: 12,
    contact_email: "tech@inpt.ac.ma",
    social_links: {
      instagram: "https://instagram.com/inpttechclub",
      linkedin: "https://linkedin.com/company/inpttechclub",
    },
    membership_open: true,
    created_at: "2019-09-15T10:00:00Z",
  },
  {
    id: 2,
    slug: "inpt-sport-club",
    name: "INPT Sport Club",
    description:
      "Le club sportif de l'INPT rassemble les passionnés de sport. Football, basketball, volleyball, tennis et running — il y en a pour tous les goûts!",
    short_description:
      "Football, basket, volley et plus — rejoins l'aventure sportive!",
    category: "sport",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2017,
    member_count: 89,
    event_count_this_year: 8,
    contact_email: "sport@inpt.ac.ma",
    social_links: {
      instagram: "https://instagram.com/inptsport",
    },
    membership_open: true,
    created_at: "2017-10-01T10:00:00Z",
  },
  {
    id: 3,
    slug: "art-vision",
    name: "Art Vision",
    description:
      "Art Vision est le club artistique de l'INPT. Photographie, design graphique, vidéo, musique — nous célébrons la créativité sous toutes ses formes.",
    short_description:
      "Photo, design, vidéo & musique — la créativité à l'INPT.",
    category: "art",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2020,
    member_count: 64,
    event_count_this_year: 6,
    contact_email: "artvision@inpt.ac.ma",
    social_links: {
      instagram: "https://instagram.com/artvision_inpt",
      facebook: "https://facebook.com/artvisioninpt",
    },
    membership_open: true,
    created_at: "2020-01-20T10:00:00Z",
  },
  {
    id: 4,
    slug: "robotics-lab",
    name: "Robotics Lab",
    description:
      "Conception, programmation et compétitions de robots. Le Robotics Lab de l'INPT participe à des compétitions nationales et internationales.",
    short_description:
      "Conception et programmation de robots — compétitions & innovation.",
    category: "science",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2018,
    member_count: 42,
    event_count_this_year: 4,
    contact_email: "robotics@inpt.ac.ma",
    social_links: {},
    membership_open: false,
    created_at: "2018-03-10T10:00:00Z",
  },
  {
    id: 5,
    slug: "enactus-inpt",
    name: "Enactus INPT",
    description:
      "Enactus INPT développe des projets d'entrepreneuriat social avec un impact positif sur la communauté. Rejoignez-nous pour changer le monde!",
    short_description:
      "Entrepreneuriat social & projets à impact positif.",
    category: "entrepreneuriat",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2016,
    member_count: 53,
    event_count_this_year: 7,
    contact_email: "enactus@inpt.ac.ma",
    social_links: {
      instagram: "https://instagram.com/enactusinpt",
      linkedin: "https://linkedin.com/company/enactusinpt",
      facebook: "https://facebook.com/enactusinpt",
    },
    membership_open: true,
    created_at: "2016-11-05T10:00:00Z",
  },
  {
    id: 6,
    slug: "solidarite-inpt",
    name: "Solidarité INPT",
    description:
      "Club social et humanitaire de l'INPT. Actions caritatives, bénévolat et initiatives solidaires pour une communauté plus unie.",
    short_description:
      "Actions solidaires, bénévolat et initiatives humanitaires.",
    category: "social",
    cover_image: null,
    logo: null,
    is_verified: false,
    founded_year: 2021,
    member_count: 35,
    event_count_this_year: 3,
    contact_email: "solidarite@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2021-02-14T10:00:00Z",
  },
];

/* ── Mock Events ─────────────────────────── */
export const MOCK_EVENTS: ClubEvent[] = [
  {
    id: 1,
    club_id: 1,
    club_slug: "inpt-tech-club",
    club_name: "INPT Tech Club",
    club_logo: null,
    title: "Workshop: Introduction à Docker & Kubernetes",
    description:
      "Apprenez les bases de la conteneurisation avec Docker et l'orchestration avec Kubernetes.",
    event_type: "workshop",
    cover_image: null,
    starts_at: "2026-04-28T14:00:00Z",
    ends_at: "2026-04-28T17:00:00Z",
    location: "Amphi A",
    is_online: false,
    max_participants: 40,
    registered_count: 32,
    is_registered: false,
    created_at: "2026-04-15T10:00:00Z",
  },
  {
    id: 2,
    club_id: 1,
    club_slug: "inpt-tech-club",
    club_name: "INPT Tech Club",
    club_logo: null,
    title: "Hackathon INPT 2026",
    description:
      "48h pour coder la solution de demain. Thème: IA pour l'éducation.",
    event_type: "hackathon",
    cover_image: null,
    starts_at: "2026-05-10T09:00:00Z",
    ends_at: "2026-05-12T18:00:00Z",
    location: null,
    is_online: false,
    max_participants: 100,
    registered_count: 67,
    is_registered: true,
    created_at: "2026-04-01T10:00:00Z",
  },
  {
    id: 3,
    club_id: 2,
    club_slug: "inpt-sport-club",
    club_name: "INPT Sport Club",
    club_logo: null,
    title: "Tournoi Inter-Filières de Football",
    description:
      "Compétition amicale entre les filières de l'INPT.",
    event_type: "competition",
    cover_image: null,
    starts_at: "2026-05-03T15:00:00Z",
    ends_at: "2026-05-03T19:00:00Z",
    location: "Terrain de sport INPT",
    is_online: false,
    max_participants: 80,
    registered_count: 45,
    is_registered: false,
    created_at: "2026-04-10T10:00:00Z",
  },
  {
    id: 4,
    club_id: 5,
    club_slug: "enactus-inpt",
    club_name: "Enactus INPT",
    club_logo: null,
    title: "Conférence: L'entrepreneuriat social au Maroc",
    description:
      "Découvrez comment l'entrepreneuriat social transforme les communautés marocaines.",
    event_type: "conference",
    cover_image: null,
    starts_at: "2026-04-30T10:00:00Z",
    ends_at: "2026-04-30T12:00:00Z",
    location: null,
    is_online: true,
    max_participants: null,
    registered_count: 23,
    is_registered: false,
    created_at: "2026-04-12T10:00:00Z",
  },
  {
    id: 5,
    club_id: 3,
    club_slug: "art-vision",
    club_name: "Art Vision",
    club_logo: null,
    title: "Atelier Photo: Maîtrisez la lumière naturelle",
    description:
      "Session pratique de photographie en extérieur.",
    event_type: "workshop",
    cover_image: null,
    starts_at: "2026-04-26T09:00:00Z",
    ends_at: "2026-04-26T12:00:00Z",
    location: "Campus INPT - Jardin",
    is_online: false,
    max_participants: 20,
    registered_count: 20,
    is_registered: false,
    created_at: "2026-04-14T10:00:00Z",
  },
];

/* ── Mock Members ────────────────────────── */
export const MOCK_MEMBERS: ClubMember[] = [
  {
    id: 1,
    user_id: 10,
    full_name: "Ahmed Benali",
    avatar: null,
    email: "ahmed.benali@inpt.ac.ma",
    filiere: "GI",
    role: "president",
    status: "active",
    joined_at: "2023-09-15T10:00:00Z",
  },
  {
    id: 2,
    user_id: 11,
    full_name: "Sara El Idrissi",
    avatar: null,
    email: "sara.elidrissi@inpt.ac.ma",
    filiere: "RT",
    role: "vice_president",
    status: "active",
    joined_at: "2023-10-01T10:00:00Z",
  },
  {
    id: 3,
    user_id: 12,
    full_name: "Youssef Amrani",
    avatar: null,
    email: "youssef.amrani@inpt.ac.ma",
    filiere: "GI",
    role: "officer",
    status: "active",
    joined_at: "2024-01-15T10:00:00Z",
  },
  {
    id: 4,
    user_id: 13,
    full_name: "Fatima Zahra Kabbaj",
    avatar: null,
    email: "fatima.kabbaj@inpt.ac.ma",
    filiere: "ISIC",
    role: "officer",
    status: "active",
    joined_at: "2024-02-20T10:00:00Z",
  },
  {
    id: 5,
    user_id: 14,
    full_name: "Omar El Fassi",
    avatar: null,
    email: "omar.elfassi@inpt.ac.ma",
    filiere: "SSE",
    role: "member",
    status: "active",
    joined_at: "2024-03-10T10:00:00Z",
  },
  {
    id: 6,
    user_id: 15,
    full_name: "Nadia Ait Ahmed",
    avatar: null,
    email: "nadia.aitahmed@inpt.ac.ma",
    filiere: "GI",
    role: "member",
    status: "active",
    joined_at: "2024-04-01T10:00:00Z",
  },
  {
    id: 7,
    user_id: 16,
    full_name: "Karim Benchekroun",
    avatar: null,
    email: "karim.benchekroun@inpt.ac.ma",
    filiere: "RT",
    role: "member",
    status: "pending",
    joined_at: "2026-04-20T10:00:00Z",
  },
];

/* ── Mock Posts ───────────────────────────── */
export const MOCK_POSTS: ClubPost[] = [
  {
    id: 1,
    club_id: 1,
    club_slug: "inpt-tech-club",
    club_name: "INPT Tech Club",
    club_logo: null,
    author_id: 10,
    author_name: "Ahmed Benali",
    author_avatar: null,
    author_role: "president",
    post_type: "annonce",
    title: "Inscriptions ouvertes pour le Hackathon 2026!",
    content:
      "Nous sommes ravis d'annoncer l'ouverture des inscriptions pour le Hackathon INPT 2026! Cette année, le thème sera 'IA pour l'éducation'. Les équipes de 3 à 5 personnes sont les bienvenues. Des prix incroyables vous attendent!",
    image: null,
    likes_count: 42,
    is_liked: true,
    created_at: "2026-04-20T14:30:00Z",
  },
  {
    id: 2,
    club_id: 1,
    club_slug: "inpt-tech-club",
    club_name: "INPT Tech Club",
    club_logo: null,
    author_id: 12,
    author_name: "Youssef Amrani",
    author_avatar: null,
    author_role: "officer",
    post_type: "recrutement",
    title: "Recherche de responsable communication",
    content:
      "Le Tech Club recrute un(e) responsable communication pour gérer nos réseaux sociaux et notre image de marque. Si tu es créatif et passionné par le digital, contacte-nous!",
    image: null,
    likes_count: 18,
    is_liked: false,
    created_at: "2026-04-18T10:00:00Z",
  },
  {
    id: 3,
    club_id: 1,
    club_slug: "inpt-tech-club",
    club_name: "INPT Tech Club",
    club_logo: null,
    author_id: 11,
    author_name: "Sara El Idrissi",
    author_avatar: null,
    author_role: "vice_president",
    post_type: "reussite",
    title: "Notre équipe finaliste au Morocco AI Challenge!",
    content:
      "Félicitations à notre équipe qui a atteint la finale du Morocco AI Challenge 2026! Un travail d'équipe exceptionnel qui fait la fierté de tout le club et de l'INPT.",
    image: null,
    likes_count: 89,
    is_liked: true,
    created_at: "2026-04-16T16:45:00Z",
  },
  {
    id: 4,
    club_id: 5,
    club_slug: "enactus-inpt",
    club_name: "Enactus INPT",
    club_logo: null,
    author_id: 20,
    author_name: "Amina Tazi",
    author_avatar: null,
    author_role: "president",
    post_type: "projet",
    title: "Lancement du projet EcoSchool",
    content:
      "Nous lançons officiellement le projet EcoSchool — une initiative pour sensibiliser les écoles primaires au développement durable à travers des ateliers interactifs.",
    image: null,
    likes_count: 31,
    is_liked: false,
    created_at: "2026-04-17T09:15:00Z",
  },
];
