import type {
  Club,
  ClubEvent,
  ClubMember,
  ClubPost,
} from "@/lib/clubs-types";

/* ── Mock Clubs ──────────────────────────── */
export const MOCK_CLUBS: Club[] = [
  {
    id: 1,
    slug: "cit",
    name: "CIT",
    description: "Le Club Informatique et Télécommunications de l'INPT. Organise des ateliers, hackathons et projets collaboratifs autour du développement logiciel, réseaux et technologies de l'information.",
    short_description: "Informatique, télécoms et projets tech.",
    category: "tech",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2012,
    member_count: 127,
    event_count_this_year: 12,
    contact_email: "cit@inpt.ac.ma",
    social_links: { instagram: "https://instagram.com/cit_inpt" },
    membership_open: true,
    created_at: "2012-09-15T10:00:00Z",
  },
  {
    id: 2,
    slug: "cas",
    name: "CAS",
    description: "Club d'Action Sociale de l'INPT. Actions caritatives, bénévolat et initiatives solidaires pour une communauté plus unie.",
    short_description: "Actions solidaires, bénévolat et initiatives humanitaires.",
    category: "social",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2015,
    member_count: 85,
    event_count_this_year: 8,
    contact_email: "cas@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2015-10-01T10:00:00Z",
  },
  {
    id: 3,
    slug: "enactus",
    name: "ENACTUS",
    description: "Enactus INPT développe des projets d'entrepreneuriat social avec un impact positif sur la communauté.",
    short_description: "Entrepreneuriat social & projets à impact positif.",
    category: "entrepreneuriat",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2014,
    member_count: 53,
    event_count_this_year: 7,
    contact_email: "enactus@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2014-11-05T10:00:00Z",
  },
  {
    id: 4,
    slug: "ibc",
    name: "IBC",
    description: "INPT Business Club accompagne les étudiants dans leurs projets entrepreneuriaux avec du mentorat, des ateliers business et des compétitions.",
    short_description: "Business, entrepreneuriat et innovation.",
    category: "entrepreneuriat",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2016,
    member_count: 64,
    event_count_this_year: 6,
    contact_email: "ibc@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2016-01-20T10:00:00Z",
  },
  {
    id: 5,
    slug: "msc",
    name: "MSC",
    description: "Le Microsoft Student Club de l'INPT. Formations sur les technologies Microsoft, certifications Azure, ateliers .NET et événements tech.",
    short_description: "Technologies Microsoft, Azure et certifications.",
    category: "tech",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2017,
    member_count: 42,
    event_count_this_year: 4,
    contact_email: "msc@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2017-03-10T10:00:00Z",
  },
  {
    id: 6,
    slug: "cese",
    name: "CESE",
    description: "Le Club des Étudiants en Sciences et Environnement mène des projets de sensibilisation et de recherche sur le développement durable et l'écologie.",
    short_description: "Sciences, environnement et développement durable.",
    category: "science",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2018,
    member_count: 35,
    event_count_this_year: 3,
    contact_email: "cese@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2018-02-14T10:00:00Z",
  },
  {
    id: 7,
    slug: "arty",
    name: "ARTY",
    description: "Le club artistique et culturel de l'INPT. Photographie, design, vidéo, musique et événements culturels pour célébrer la créativité.",
    short_description: "Art, culture et créativité.",
    category: "art",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2015,
    member_count: 40,
    event_count_this_year: 5,
    contact_email: "arty@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2015-05-14T10:00:00Z",
  },
  {
    id: 8,
    slug: "a2s",
    name: "A2S",
    description: "A2S JUNIOR ENTREPRISE",
    short_description: "La junior entreprise de l'INPT",
    category: "freelance",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2010,
    member_count: 150,
    event_count_this_year: 15,
    contact_email: "a2s@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2010-09-14T10:00:00Z",
  },
  {
    id: 9,
    slug: "ieee",
    name: "IEEE",
    description: "IEEE Student Branch INPT. Favorise l'innovation technologique et l'excellence au profit de l'humanité à travers des projets et conférences.",
    short_description: "Innovation technologique et excellence.",
    category: "tech",
    cover_image: null,
    logo: null,
    is_verified: true,
    founded_year: 2019,
    member_count: 55,
    event_count_this_year: 4,
    contact_email: "ieee@inpt.ac.ma",
    social_links: {},
    membership_open: true,
    created_at: "2019-09-14T10:00:00Z",
  }
];

/* ── Mock Events ─────────────────────────── */
export const MOCK_EVENTS: ClubEvent[] = [
  {
    id: 1,
    club_id: 1,
    club_slug: "cit",
    club_name: "CIT",
    club_logo: null,
    title: "Workshop: Introduction à Docker & Kubernetes",
    description:
      "Apprenez les bases de la conteneurisation avec Docker et l'orchestration avec Kubernetes.",
    event_type: "workshop",
    cover_image: null,
    starts_at: "2026-04-28T14:00:00Z",
    ends_at: "2026-04-28T17:00:00Z",
    location: "Amphi A",
    is_online: false,
    max_participants: 40,
    registered_count: 32,
    is_registered: false,
    created_at: "2026-04-15T10:00:00Z",
  },
  {
    id: 2,
    club_id: 1,
    club_slug: "cit",
    club_name: "CIT",
    club_logo: null,
    title: "Hackathon INPT 2026",
    description:
      "48h pour coder la solution de demain. Thème: IA pour l'éducation.",
    event_type: "hackathon",
    cover_image: null,
    starts_at: "2026-05-10T09:00:00Z",
    ends_at: "2026-05-12T18:00:00Z",
    location: null,
    is_online: false,
    max_participants: 100,
    registered_count: 67,
    is_registered: true,
    created_at: "2026-04-01T10:00:00Z",
  },
  {
    id: 3,
    club_id: 8,
    club_slug: "a2s",
    club_name: "A2S",
    club_logo: null,
    title: "Tournoi Inter-Filières de Football",
    description:
      "Compétition amicale entre les filières de l'INPT.",
    event_type: "competition",
    cover_image: null,
    starts_at: "2026-05-03T15:00:00Z",
    ends_at: "2026-05-03T19:00:00Z",
    location: "Terrain de sport INPT",
    is_online: false,
    max_participants: 80,
    registered_count: 45,
    is_registered: false,
    created_at: "2026-04-10T10:00:00Z",
  },
  {
    id: 4,
    club_id: 3,
    club_slug: "enactus",
    club_name: "ENACTUS",
    club_logo: null,
    title: "Conférence: L'entrepreneuriat social au Maroc",
    description:
      "Découvrez comment l'entrepreneuriat social transforme les communautés marocaines.",
    event_type: "conference",
    cover_image: null,
    starts_at: "2026-04-30T10:00:00Z",
    ends_at: "2026-04-30T12:00:00Z",
    location: null,
    is_online: true,
    max_participants: null,
    registered_count: 23,
    is_registered: false,
    created_at: "2026-04-12T10:00:00Z",
  },
  {
    id: 5,
    club_id: 7,
    club_slug: "arty",
    club_name: "ARTY",
    club_logo: null,
    title: "Atelier Photo: Maîtrisez la lumière naturelle",
    description:
      "Session pratique de photographie en extérieur.",
    event_type: "workshop",
    cover_image: null,
    starts_at: "2026-04-26T09:00:00Z",
    ends_at: "2026-04-26T12:00:00Z",
    location: "Campus INPT - Jardin",
    is_online: false,
    max_participants: 20,
    registered_count: 20,
    is_registered: false,
    created_at: "2026-04-14T10:00:00Z",
  },
];

/* ── Mock Members ────────────────────────── */
export const MOCK_MEMBERS: ClubMember[] = [
  {
    id: 1,
    user_id: 10,
    full_name: "Ahmed Benali",
    avatar: null,
    email: "ahmed.benali@inpt.ac.ma",
    filiere: "GI",
    role: "president",
    status: "active",
    joined_at: "2023-09-15T10:00:00Z",
  },
  {
    id: 2,
    user_id: 11,
    full_name: "Sara El Idrissi",
    avatar: null,
    email: "sara.elidrissi@inpt.ac.ma",
    filiere: "RT",
    role: "vice_president",
    status: "active",
    joined_at: "2023-10-01T10:00:00Z",
  },
  {
    id: 3,
    user_id: 12,
    full_name: "Youssef Amrani",
    avatar: null,
    email: "youssef.amrani@inpt.ac.ma",
    filiere: "GI",
    role: "officer",
    status: "active",
    joined_at: "2024-01-15T10:00:00Z",
  },
  {
    id: 4,
    user_id: 13,
    full_name: "Fatima Zahra Kabbaj",
    avatar: null,
    email: "fatima.kabbaj@inpt.ac.ma",
    filiere: "ISIC",
    role: "officer",
    status: "active",
    joined_at: "2024-02-20T10:00:00Z",
  },
  {
    id: 5,
    user_id: 14,
    full_name: "Omar El Fassi",
    avatar: null,
    email: "omar.elfassi@inpt.ac.ma",
    filiere: "SSE",
    role: "member",
    status: "active",
    joined_at: "2024-03-10T10:00:00Z",
  },
  {
    id: 6,
    user_id: 15,
    full_name: "Nadia Ait Ahmed",
    avatar: null,
    email: "nadia.aitahmed@inpt.ac.ma",
    filiere: "GI",
    role: "member",
    status: "active",
    joined_at: "2024-04-01T10:00:00Z",
  },
  {
    id: 7,
    user_id: 16,
    full_name: "Karim Benchekroun",
    avatar: null,
    email: "karim.benchekroun@inpt.ac.ma",
    filiere: "RT",
    role: "member",
    status: "pending",
    joined_at: "2026-04-20T10:00:00Z",
  },
];

/* ── Mock Posts ───────────────────────────── */
export const MOCK_POSTS: ClubPost[] = [
  {
    id: 1,
    club_id: 1,
    club_slug: "cit",
    club_name: "CIT",
    club_logo: null,
    author_id: 10,
    author_name: "Ahmed Benali",
    author_avatar: null,
    author_role: "president",
    post_type: "annonce",
    title: "Inscriptions ouvertes pour le Hackathon 2026!",
    content:
      "Nous sommes ravis d'annoncer l'ouverture des inscriptions pour le Hackathon INPT 2026! Cette année, le thème sera 'IA pour l'éducation'. Les équipes de 3 à 5 personnes sont les bienvenues. Des prix incroyables vous attendent!",
    image: null,
    likes_count: 42,
    is_liked: true,
    created_at: "2026-04-20T14:30:00Z",
  },
  {
    id: 2,
    club_id: 1,
    club_slug: "cit",
    club_name: "CIT",
    club_logo: null,
    author_id: 12,
    author_name: "Youssef Amrani",
    author_avatar: null,
    author_role: "officer",
    post_type: "recrutement",
    title: "Recherche de responsable communication",
    content:
      "Le Tech Club recrute un(e) responsable communication pour gérer nos réseaux sociaux et notre image de marque. Si tu es créatif et passionné par le digital, contacte-nous!",
    image: null,
    likes_count: 18,
    is_liked: false,
    created_at: "2026-04-18T10:00:00Z",
  },
  {
    id: 3,
    club_id: 1,
    club_slug: "cit",
    club_name: "CIT",
    club_logo: null,
    author_id: 11,
    author_name: "Sara El Idrissi",
    author_avatar: null,
    author_role: "vice_president",
    post_type: "reussite",
    title: "Notre équipe finaliste au Morocco AI Challenge!",
    content:
      "Félicitations à notre équipe qui a atteint la finale du Morocco AI Challenge 2026! Un travail d'équipe exceptionnel qui fait la fierté de tout le club et de l'INPT.",
    image: null,
    likes_count: 89,
    is_liked: true,
    created_at: "2026-04-16T16:45:00Z",
  },
  {
    id: 4,
    club_id: 3,
    club_slug: "enactus",
    club_name: "ENACTUS",
    club_logo: null,
    author_id: 20,
    author_name: "Amina Tazi",
    author_avatar: null,
    author_role: "president",
    post_type: "projet",
    title: "Lancement du projet EcoSchool",
    content:
      "Nous lançons officiellement le projet EcoSchool — une initiative pour sensibiliser les écoles primaires au développement durable à travers des ateliers interactifs.",
    image: null,
    likes_count: 31,
    is_liked: false,
    created_at: "2026-04-17T09:15:00Z",
  },
];
